### PR TITLE
Modernize PDF

### PR DESCRIPTION
**Pull request by cameroncuster**

### CODE REVIEW

**Comment by lrvideckis** [comment]
Update the link to the PDF in the main readme

**Comment by lrvideckis** [comment]
Do you plan to do any more of your issues, or is this the final PDF for now?

**Comment by cameroncuster** [comment]
Not sure, just trying to iterate on it.

**Comment by cameroncuster** [comment]
I touched it up a bit, gonna add a few more things and fix the link, then merge.

**Pull request merged**
